### ISSUE TITLE
Edge data should be included as output

### ISSUE THREAD

**Issue by TrystanScottLambert** [TrystanScottLambert/pyFoF#6]
Edge data should be included as output, that we it can use it in 3D visualization.

**Comment by BrutishGuy** [comment]
How easy would it be to do this? I think it's not such a tough thing to implement - not sure if currently store the edge list? If not, we can just track it while we build the cluster or at the end of the cluster. Also, via what principle do we build edges? Do we follow friends-of-friends in some way as it's  building the clusters or is it as simple as taking each final cluster, making it a fully-connected sub-graph for all galaxies in that cluster?

**Comment by TrystanScottLambert** [comment]
I think is very easy to do. I just noticed now that the "edge_data" variable which contains all of the edge data that we need is never used in the experiment module. I probably started to get this done, got the difficult part of getting the edge data together, and never bothered to output said data.

**Comment by TrystanScottLambert** [comment]
Edge data is now an output. @BrutishGuy, time to merge dev with main and push the new package.

**Comment by TrystanScottLambert** [comment]
Edge data can now be printed. Instructions have been updated in the README
