### ISSUE TITLE
Reading in fits files isn't working

### ISSUE THREAD

**Issue by Wes2799** [TrystanScottLambert/pyFoF#61]
Error when using .fits files for data input. The formatting of the variables (ra, dec, etc.) are not correctly read in. It reads in these values as integers instead of float and string is prefixed by a "b" then the text in inverted commas e.g b'text'.

**Comment by TrystanScottLambert** [comment]
Thanks. This is a problem with the way that data_handling reads in fits tables and specifically how we convert the data into the proper data types. The "auto_convert_df_types" method is converting float arrays into int arrays where we expected that it would raise a ValueError. 

I'll fix the function and it'll come out in the new release. This is also the second time we've had an issue with reading in fits tables, so we need to seriously write some tests to make sure that the data_handling module is working once and for all.

**Comment by TrystanScottLambert** [comment]
I've updated the function and it seems to be working now. We will need to write some tests and the fix can come out in the new version. Probably next week. In the meantime it's suggested to only use text files and don't use fits tables until the next release.
