### ISSUE TITLE
FITS File Data Read in as Integer

### ISSUE THREAD

**Issue by Wes2799** [TrystanScottLambert/pyFoF#65]
If the input file is a .fits file, the read_data function converts all the fits data values to integers, whereas if the input file is a .tbl, it does not do this.

**Comment by TrystanScottLambert** [comment]
Whats the name of the fits file you are using? I'll give it a try my side.

**Comment by Wes2799** [comment]
TAO_1.fits

**Comment by TrystanScottLambert** [comment]
Could you email me the fits file that you're using and I'll give it a try? Using the KIDS example, are can't replicate the error.

**Comment by TrystanScottLambert** [comment]
I've tried reading in a fits file from another survey and we still have this error. I'm sure we had fixed this before but I think there was an issue with one of the branch mergers which undid the fix. The new fix will be coming soon.

**Comment by TrystanScottLambert** [comment]
@BrutishGuy, looking at the data handling I notice this line:

```python
def infer_dtype(value: str) -> Union[str, int, float]:
    try:
        int(value)
        return int
    except ValueError:
        pass

    try:
        float(value)
        return float
    except ValueError:
        pass

    return str
```

The try and except catches are never going to fail for ints and floats. And we will actually round down any float values. i.e. if we have redshifts which are all  < 1 then we will return them as zeros. int(0.5) = 0. So this is why when we automatically read in things that we are only seeing ints instead of floats.

**Comment by TrystanScottLambert** [comment]
@BrutishGuy what I think might be a better work around is to use ``ast''

i.e.,:

```python
import ast

def infer_dtype(value: str) -> Union[str, int, float]:
    try:
        val = type(ast.literal_eval(value))
        return val
    except ValueError:
        pass
    return str
```

I think that this works. the ```ast.literal_eval``` line should return int/float depending on the actual value. Then when we asign these values based on their inferred types later, we shouldn't be making floats ints. 


What do you think?

**Comment by TrystanScottLambert** [comment]
@BrutishGuy I'm a little confused too because the read_fits fix branch works, but that code is hashed out in main? So we either need to implement this fix I've mentioned or merge again with the read_fits_fix code. Thanks :)

**Comment by BrutishGuy** [comment]
I agree with the fix you mention. I’ll test it out during the day and push a fix for you to review.

**Comment by TrystanScottLambert** [comment]
@BrutishGuy push everything to the dev branch because I'm close to getting the speck file output finished. Then I'll just test everything at once on the dev branch and let you know. Hopefully new version by the end of the week :)

**Comment by BrutishGuy** [comment]
I've created a PR for the above. Awaiting a review on that. Added test cases to hopefully catch issues in future.

**Comment by TrystanScottLambert** [comment]
@BrutishGuy  I've merged the branch. Let's push the new package when you can. Thanks.

**Comment by TrystanScottLambert** [comment]
@BrutishGuy @Wes2799 I just did a run using the deve branch and I think this bug is finally fixed. New package will be able to read the fits files correctly. 1.0.12.
