### ISSUE TITLE
Better to split up experiement into experiment and run classes to be more transparent.

### ISSUE THREAD

**Issue by TrystanScottLambert** [TrystanScottLambert/pyFoF#8]
At the moment the function _run_ is run when the experiemnt class is initialized. It would be better to split up the class so that we set up the experiement and then run it via another class.

**Comment by BrutishGuy** [comment]
Refactoring this in the latest release, v1.0.8.

**Comment by TrystanScottLambert** [comment]
Done and included in the readme.
